service: api

custom:
  stage: ${opt:stage, 'local'}
  env: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: ${self:custom.stage}
  environment:
    ELASTIC_SEARCH: ${self:custom.env.elasticsearch}
    SLS_DEBUG: '*'
  httpApi:
    cors: true
  vpc: ${self:custom.env.vpc}
  versionFunctions: false

functions:
  globalSnapshot:
    handler: src/handler.globalSnapshot
    events:
      - httpApi:
          path: /global-snapshot/{term}
          method: GET
  globalSnapshotRewards:
    handler: src/handler.globalSnapshotRewards
    events:
      - httpApi:
          path: /global-snapshot/latest/rewards
          method: GET
  balanceByAddress:
    handler: src/handler.balanceByAddress
    events:
      - httpApi:
          path: /address/{term}/balance
          method: GET

plugins:
  - serverless-plugin-typescript