service: api

custom:
  stage: ${opt:stage, 'local'}
  env: ${file(env.yml):${self:custom.stage}, file(env.yml):default}
  # set serverless offline http port, since default port 3000 is already in use by Grafana in the local tessellation cluster
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1
  stage: ${self:custom.stage}
  environment:
    SLS_DEBUG: "*"
    DATABASE_URL: ${self:custom.env.db_url}
  httpApi:
    cors: true
  vpc: ${self:custom.env.vpc}
  versionFunctions: false
  timeout: 60

functions:
  - ${file(./routes/dag.yml)}
  - ${file(./routes/metagraph.yml)}
  - ${file(./routes/token-locks.yml)}
  - ${file(./routes/allow-spends.yml)}
  - ${file(./routes/actions.yml)}
  - ${file(./routes/delegated-staking.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
