service: api

custom:
  stage: ${opt:stage, 'local'}
  env: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: ${self:custom.stage}
  environment:
    OPENSEARCH_NODE: ${self:custom.env.opensearch}
    SLS_DEBUG: '*'
  httpApi:
    cors: true
  vpc: ${self:custom.env.vpc}
  versionFunctions: false

functions:
  globalSnapshot:
    handler: src/handler.globalSnapshot
    events:
      - httpApi:
          path: /global-snapshot/{term}
          method: GET
  globalSnapshotRewards:
    handler: src/handler.globalSnapshotRewards
    events:
      - httpApi:
          path: /global-snapshot/latest/rewards
          method: GET
  globalSnapshotTransactions:
    handler: src/handler.globalSnapshotTransactions
    events:
      - httpApi:
          path: /global-snapshot/{term}/transaction
          method: GET
  block:
    handler: src/handler.block
    events:
      - httpApi:
          path: /block/{hash}
          method: GET
  transaction:
    handler: src/handler.transaction
    events:
      - httpApi:
          path: /transaction/{hash}
          method: GET
  transactionsByAddress:
    handler: src/handler.transactionsByAddress
    events:
      - httpApi:
          path: /address/{address}/transaction
          method: GET
  transactionsBySource:
    handler: src/handler.transactionsBySource
    events:
      - httpApi:
          path: /address/{address}/transaction/sent
          method: GET
  transactionsByDestination:
    handler: src/handler.transactionsByDestination
    events:
      - httpApi:
          path: /address/{address}/transaction/received
          method: GET
  balanceByAddress:
    handler: src/handler.balanceByAddress
    events:
      - httpApi:
          path: /address/{address}/balance/
          method: GET

plugins:
  - serverless-plugin-typescript