service: api

custom:
  stage: ${opt:stage, 'local'}
  env: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: ${self:custom.stage}
  environment:
    ELASTIC_SEARCH: ${self:custom.env.elasticsearch}
    SLS_DEBUG: '*'
  httpApi:
    cors: true
  vpc: ${self:custom.env.vpc}
  versionFunctions: false

functions:
  snapshots:
    handler: src/handler.snapshots
    events:
      - httpApi:
          path: /snapshot/{term}
          method: GET
  checkpoint-blocks:
    handler: src/handler.checkpointBlocks
    events:
      - httpApi:
          path: /checkpoint-block/{term}
          method: GET
  transactions:
    handler: src/handler.transactions
    events:
      - httpApi:
          path: /transaction/{term}
          method: GET
  transactionsBySnapshot:
    handler: src/handler.transactionsBySnapshot
    events:
      - httpApi:
          path: /snapshot/{term}/transaction
          method: GET
  transactionsByAddress:
    handler: src/handler.transactionsByAddress
    events:
      - httpApi:
          path: /address/{term}/transaction
          method: GET
  transactionsBySender:
    handler: src/handler.transactionsBySender
    events:
      - httpApi:
          path: /address/{term}/transaction/sent
          method: GET
  transactionsByReceiver:
    handler: src/handler.transactionsByReceiver
    events:
      - httpApi:
          path: /address/{term}/transaction/received
          method: GET

plugins:
  - serverless-plugin-typescript