service: api

custom:
  stage: ${opt:stage, 'local'}
  env: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  stage: ${self:custom.stage}
  environment:
    OPENSEARCH_NODE: ${self:custom.env.opensearch}
    SLS_DEBUG: '*'
  httpApi:
    cors: true
  vpc: ${self:custom.env.vpc}
  versionFunctions: false

functions:
  globalSnapshot:
    handler: src/handler.globalSnapshot
    events:
      - httpApi:
          path: /global-snapshots/{term}
          method: GET
          cors: true
  globalSnapshotRewards:
    handler: src/handler.globalSnapshotRewards
    events:
      - httpApi:
          path: /global-snapshots/latest/rewards
          method: GET
          cors: true
  globalSnapshotTransactions:
    handler: src/handler.globalSnapshotTransactions
    events:
      - httpApi:
          path: /global-snapshots/{term}/transactions
          method: GET
          cors: true
  block:
    handler: src/handler.block
    events:
      - httpApi:
          path: /blocks/{hash}
          method: GET
          cors: true
  transaction:
    handler: src/handler.transaction
    events:
      - httpApi:
          path: /transactions/{hash}
          method: GET
          cors: true
  transactionsByAddress:
    handler: src/handler.transactionsByAddress
    events:
      - httpApi:
          path: /addresses/{address}/transactions
          method: GET
          cors: true
  transactionsBySource:
    handler: src/handler.transactionsBySource
    events:
      - httpApi:
          path: /addresses/{address}/transactions/sent
          method: GET
          cors: true
  transactionsByDestination:
    handler: src/handler.transactionsByDestination
    events:
      - httpApi:
          path: /addresses/{address}/transactions/received
          method: GET
          cors: true
  balanceByAddress:
    handler: src/handler.balanceByAddress
    events:
      - httpApi:
          path: /addresses/{address}/balances
          method: GET
          cors: true

plugins:
  - serverless-plugin-typescript
