service: api

custom:
  stage: ${opt:stage, 'local'}
  env: ${file(env.yml):${self:custom.stage}, file(env.yml):default}
  # set serverless offline http port, since default port 3000 is already in use by Grafana in the local tessellation cluster
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1
  stage: ${self:custom.stage}
  environment:
    SLS_DEBUG: '*'
  httpApi:
    cors: true
  vpc: ${self:custom.env.vpc}
  versionFunctions: false
  timeout: 10

functions:
  globalSnapshots:
    handler: src/handler.handleGlobalSnapshots
    events:
      - httpApi:
          path: /global-snapshots
          method: GET
  globalSnapshot:
    handler: src/handler.handleGlobalSnapshot
    events:
      - httpApi:
          path: /global-snapshots/{term}
          method: GET
  globalSnapshotRewards:
    handler: src/handler.handleGlobalSnapshotRewards
    events:
      - httpApi:
          path: /global-snapshots/{term}/rewards
          method: GET
  globalSnapshotTransactions:
    handler: src/handler.handleGlobalSnapshotTransactions
    events:
      - httpApi:
          path: /global-snapshots/{term}/transactions
          method: GET
  block:
    handler: src/handler.handleDagBlock
    events:
      - httpApi:
          path: /blocks/{hash}
          method: GET
  transactions:
    handler: src/handler.handleDagTransactions
    events:
      - httpApi:
          path: /transactions
          method: GET
  transaction:
    handler: src/handler.handleDagTransaction
    events:
      - httpApi:
          path: /transactions/{hash}
          method: GET
  transactionsByAddress:
    handler: src/handler.handleDagTransactionsByAddress
    events:
      - httpApi:
          path: /addresses/{address}/transactions
          method: GET
  transactionsBySource:
    handler: src/handler.handleDagTransactionsBySource
    events:
      - httpApi:
          path: /addresses/{address}/transactions/sent
          method: GET
  transactionsByDestination:
    handler: src/handler.handleDagTransactionsByDestination
    events:
      - httpApi:
          path: /addresses/{address}/transactions/received
          method: GET
  balanceByAddress:
    handler: src/handler.handleDagBalanceByAddress
    events:
      - httpApi:
          path: /addresses/{address}/balance
          method: GET

  currencySnapshots:
    handler: src/handler.handleCurrencySnapshots
    events:
      - httpApi:
          path: /currency/{identifier}/snapshots
          method: GET
  currencySnapshotsByOwnerAddress:
    handler: src/handler.handleCurrencySnapshotsByOwnerAddress
    events:
      - httpApi:
          path: /addresses/{address}/snapshots
          method: GET
  currencySnapshot:
    handler: src/handler.handleCurrencySnapshot
    events:
      - httpApi:
          path: /currency/{identifier}/snapshots/{term}
          method: GET
  currencySnapshotRewards:
    handler: src/handler.handleCurrencySnapshotRewards
    events:
      - httpApi:
          path: /currency/{identifier}/snapshots/{term}/rewards
          method: GET
  currencySnapshotTransactions:
    handler: src/handler.handleCurrencySnapshotTransactions
    events:
      - httpApi:
          path: /currency/{identifier}/snapshots/{term}/transactions
          method: GET
  currencyBlock:
    handler: src/handler.handleCurrencyBlock
    events:
      - httpApi:
          path: /currency/{identifier}/blocks/{hash}
          method: GET
  currencyTransactions:
    handler: src/handler.handleCurrencyTransactions
    events:
      - httpApi:
          path: /currency/{identifier}/transactions
          method: GET
  currencyTransaction:
    handler: src/handler.handleCurrencyTransaction
    events:
      - httpApi:
          path: /currency/{identifier}/transactions/{hash}
          method: GET
  currencyTransactionsByAddress:
    handler: src/handler.handleCurrencyTransactionsByAddress
    events:
      - httpApi:
          path: /currency/{identifier}/addresses/{address}/transactions
          method: GET
  currencyTransactionsBySource:
    handler: src/handler.handleCurrencyTransactionsBySource
    events:
      - httpApi:
          path: /currency/{identifier}/addresses/{address}/transactions/sent
          method: GET
  currencyTransactionsByDestination:
    handler: src/handler.handleCurrencyTransactionsByDestination
    events:
      - httpApi:
          path: /currency/{identifier}/addresses/{address}/transactions/received
          method: GET
  currencyBalanceByAddress:
    handler: src/handler.handleCurrencyBalanceByAddress
    events:
      - httpApi:
          path: /currency/{identifier}/addresses/{address}/balance
          method: GET
  currencyFeeTransaction:
    handler: src/handler.handleCurrencyFeeTransaction
    events:
      - httpApi:
          path: /currency/{identifier}/fee-transactions/{hash}
          method: GET
  currencySnapshotFeeTransactions:
    handler: src/handler.handleCurrencySnapshotFeeTransactions
    events:
      - httpApi:
          path: /currency/{identifier}/snapshots/{term}/fee-transactions
          method: GET
  currencyFeeTransactionsByAddress:
    handler: src/handler.handleCurrencyFeeTransactionsByAddress
    events:
      - httpApi:
          path: /currency/{identifier}/addresses/{address}/fee-transactions
          method: GET
  currencyFeeTransactionsBySource:
    handler: src/handler.handleCurrencyFeeTransactionsBySource
    events:
      - httpApi:
          path: /currency/{identifier}/addresses/{address}/fee-transactions/sent
          method: GET
  currencyFeeTransactionsByDestination:
    handler: src/handler.handleCurrencyFeeTransactionsByDestination
    events:
      - httpApi:
          path: /currency/{identifier}/addresses/{address}/fee-transactions/received
          method: GET
  metagraphs:
    handler: src/handler.metagraphs
    events:
      - httpApi:
          path: /currency
          method: GET

plugins:
  - serverless-plugin-typescript
  - serverless-offline
