on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: environment
        required: true

name: Deploy app from tag

jobs:
  deploy:
    name: Deploy serverless
    runs-on: ubuntu-20.04
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          cat > env.yml << EOF
          ${{ secrets.API_ENV }}
          EOF

      - name: Deploy to ${{ inputs.environment }}
        uses: serverless/github-action@v3
        with:
          args: deploy --stage ${{ inputs.environment }}20 --region us-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
