on:
  push:
    branches:
      - develop

name: Deploy dev serverless

jobs:
  deploy:
    name: Deploy serverless
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run test:tsc

      - name: Test
        run: npm test -- --coverage --ci

      - name: Create env file
        run: |
          cat > env.yml << EOF
          ${{ secrets.API_ENV }}
          EOF

      - name: Deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage dev --region us-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
