on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: API - deploy serverless

jobs:
  deploy:
    name: Deploy serverless
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: "v(.*)"
          tagRegexGroup: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Compile
        working-directory: ./api
        run: npm run typecheck

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tagName.outputs.tag }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create env file
        working-directory: ./api
        run: |
          cat > env.yml << EOF
          ${{ secrets.API_ENV }}
          EOF

      - name: Deploy
        working-direcotry: ./api
        uses: serverless/github-action@master
        with:
          args: deploy --stage mainnet --region us-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}